// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVKdJ1jExRUrRhv824ucAmumvi2wxT71c',
    appId: '1:596077333833:web:460172db368ef04d301e98',
    messagingSenderId: '596077333833',
    projectId: 'envubi-2f120',
    authDomain: 'envubi-2f120.firebaseapp.com',
    storageBucket: 'envubi-2f120.appspot.com',
    measurementId: 'G-44BQP1RLPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsu1bakU1Nh1MlY8sYwMvPs-Sc0TnZQVk',
    appId: '1:596077333833:android:5d793c7ba0794091301e98',
    messagingSenderId: '596077333833',
    projectId: 'envubi-2f120',
    storageBucket: 'envubi-2f120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK6PjsH78w7bKv-C2SIodDG-NsHruEv6E',
    appId: '1:596077333833:ios:86b8eed7cf019b42301e98',
    messagingSenderId: '596077333833',
    projectId: 'envubi-2f120',
    storageBucket: 'envubi-2f120.appspot.com',
    iosClientId: '596077333833-q8r2g9c4gs20s5r4bj2omfpi8b40af9e.apps.googleusercontent.com',
    iosBundleId: 'dev.flutterexplained.envubi',
  );
}
