name: envubi

on: [ pull_request ]

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 2.10.0
      coverage_excludes: "lib/l10n/l10n.dart"
